name: Bump Signet SDK Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump_version:
    name: Bump version and create tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Bump version
        id: bump_version
        run: |
          cd packages/signet-sdk
          
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          
          # Bump version based on input
          VERSION_TYPE=${{ github.event.inputs.version }}
          
          # Split version into components
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          if [ "$VERSION_TYPE" == "major" ]; then
            NEW_VERSION="$((MAJOR + 1)).0.0"
          elif [ "$VERSION_TYPE" == "minor" ]; then
            NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
          else
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
          # Update package.json
          npm version $NEW_VERSION --no-git-tag-version
      
      - name: Commit changes
        run: |
          git add packages/signet-sdk/package.json
          git commit -m "chore: bump signet-sdk version to ${{ env.NEW_VERSION }}"
          git push
      
      - name: Create tag
        run: |
          git tag "signet-sdk-v${{ env.NEW_VERSION }}"
          git push origin "signet-sdk-v${{ env.NEW_VERSION }}"
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "signet-sdk-v${{ env.NEW_VERSION }}"
          release_name: "Signet SDK v${{ env.NEW_VERSION }}"
          draft: false
          prerelease: false
          body: |
            # Signet SDK v${{ env.NEW_VERSION }}
            
            ## Changes
            
            - ${{ github.event.inputs.version }} version update
            
            ## How to install
            
            ```bash
            npm install signet-sdk@${{ env.NEW_VERSION }}
            # or
            yarn add signet-sdk@${{ env.NEW_VERSION }}
            # or
            pnpm add signet-sdk@${{ env.NEW_VERSION }}
            ```