name: Update Signet SDK README

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update_readme:
    name: Update README with latest version
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/signet-sdk-v')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Extract version
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/signet-sdk-v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        
      - name: Update README version
        run: |
          # Update version references in README
          sed -i "s/npm install signet-sdk@[0-9.]\+/npm install signet-sdk@$VERSION/g" packages/signet-sdk/README.md
          sed -i "s/\"signet-sdk\": \"[^\"]\+\"/\"signet-sdk\": \"^$VERSION\"/g" packages/signet-sdk/README.md
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add packages/signet-sdk/README.md
          git commit -m "docs: update Signet SDK README to version $VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}